version: '3.3'

services:
  tg:
    container_name: tg
    build: ./
    volumes:
      - ./:/secret_santa
    command: python3 src/bot/main.py

  web:
    container_name: web
    build: ./
    command: python3 src/web/main.py
    volumes:
      - ./:/secret_santa
    ports:
      - ${WEB_PORT}:8000
    depends_on:
      - db
      - tg

  db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - santa_db:/var/lib/postgresql/data
    restart: always

volumes:
  santa_db: